
literal ::= int_lit | real_lit | char_lit | string_lit

identifier ::= unders_in_paren? id_start id_cont* digit? unders_in_paren?

simple_id ::= id_start digit?

lower_or_under ::= lower | '_'

id_start ::= lower lower_or_under*

id_cont ::= unders_in_paren lower_or_under+

unders_in_paren ::= '(_' ( comma '_' )* ')'

opt_space ::= ' '?

comma ::= ',' opt_space

paren_start ::= '(' opt_space

paren_end ::= opt_space ')'

line_op_or_func_expr ::= line_op_expr | line_func_expr

paren_expr ::= paren_start line_op_or_func_expr paren_end

tuple ::= paren_start line_expr_or_under comma line_expr_or_unders paren_end

line_expr_or_unders ::= line_expr_or_under ( comma line_expr_or_under )*

line_expr_or_under ::= line_expr | '_'

line_expr ::= basic_or_app_expr | line_op_or_func_expr

basic_or_app_expr ::= basic_expr | pre_func_app | post_func_app

basic_expr ::= literal | paren_func_app_or_id | special_id | tuple | list

nl_indent ::= nl indent

big_tuple ::=
paren_start line_expr_or_under nl_indent?
comma line_expr_or_unders
( nl_indent comma line_expr_or_unders )*
nl_indent ')'

sq_brack_start ::= '[' opt_space

sq_brack_end ::= opt_space ']'

list ::= sq_brack_start line_expr_or_unders? sq_brack_end

big_list ::=
sq_brack_start line_expr_or_unders
( nl_indent comma line_expr_or_unders )* nl_indent ']'

paren_func_app_or_id ::=
arguments? id_start ( arguments lower_or_under+ )* digit? arguments?

arguments ::= paren_start line_expr_or_unders paren_end

pre_func ::= simple_id '--'

pre_func_app ::= pre_func operand

post_func ::= '.' simple_or_special_id

simple_or_special_id ::= simple_id | special_id

special_id ::= '1st' | '2nd' | '3rd' | '4th' | '5th'

post_func_app ::=
( basic_expr | paren_expr | '_' )
( dot_change | post_func+ dot_change? )

dot_change ::=
'.change{' opt_space field_change ( comma field_change )* opt_space '}'

field_change ::= simple_or_special_id equals line_expr_or_under

equals ::= opt_space '=' opt_space

op_expr ::= line_op_expr | big_op_expr

line_op_expr_start ::= ( operand op )+

line_op_expr ::= line_op_expr_start ( operand | line_func_expr )

big_op_expr ::= big_op_expr_op_split | big_op_expr_func_split

big_op_expr_op_split ::=
op_split_line+ line_op_expr_start? ( operand | func_expr )

op_split_line ::=
( line_op_expr_start ( nl | oper_fco_nl ) | oper_fco_nl ) indent

oper_fco_nl ::= operand ' ' func_comp_op '\n'

big_op_expr_func_split ::= line_op_expr_start ( big_func_expr | cases_func_expr )

operand ::= basic_or_app_expr | paren_expr | '_'

op ::= ' ' func_comp_op ' ' | opt_space optional_spaces_op opt_space

func_comp_op ::= 'o>' | '<o'

optional_spaces_op ::=
'->' | '<-' | '^' | '*' | '/' | '+' | '-' | '==' | '!=' | '>' | '<' | '>=' |
'<=' | '&' | '|' | '>>' | ';'

func_expr ::= line_func_expr | big_func_expr | cases_func_expr

func_arrow ::= opt_space '=>' opt_space

parameters_arrow ::= parameters func_arrow

line_func_expr ::= parameters_arrow line_func_body

big_func_expr ::= parameters_arrow big_func_body

parameters ::=
identifier | '*' | paren_start parameters ( comma parameters )+ paren_end

line_func_body ::=
basic_or_app_expr | line_op_expr | paren_line_func_expr

paren_line_func_expr ::= paren_start line_func_expr paren_end

big_func_body ::=
nl_indent ( basic_or_app_expr | op_expr | paren_line_func_expr )

cases_func_expr ::= cases_params case+ end_case?

cases_params ::=
identifier | '?' | '*' |
paren_start cases_params ( comma cases_params )+ paren_end

case ::= nl_indent (simple_id | matching) func_arrow case_body

end_case ::= nl_indent ( '...' | identifier ) func_arrow case_body

matching ::= literal | pre_func inner_matching | tuple_matching | list_matching

inner_matching ::= '*' | identifier | matching

tuple_matching ::= paren_start inner_matching ( comma inner_matching )+ paren_end

list_matching ::=
sq_brack_start
(inner_matching ( comma inner_matching )* rest_list_matching?)?
sq_brack_end

rest_list_matching ::= comma (simple_id equals)? '...'

case_body ::= line_func_body | big_func_body where_expr?

has_type ::= (opt_space | nl_indent) ':' opt_space

nl_indent_equals ::= nl_indent '= '

value_def ::= identifier has_type type value_equals?

value_equals ::= nl_indent_equals value_expr where_expr?

value_expr ::=
basic_or_app_expr | op_expr | func_expr | big_tuple | big_list

types ::=  type ( comma type )+ | 'all ' type

lines_exprs ::= line_exprs ( nl_indent comma line_exprs )*

grouped_value_defs ::= identifiers has_type types nl_indent_equals lines_exprs

identifiers ::= identifier ( comma identifier )+

line_exprs ::= line_expr ( comma line_expr )*

where_expr ::=
nl_indent 'where' nl value_def_or_defs ( nl nl value_def_or_defs )*

value_def_or_defs ::= indent (value_def | grouped_value_defs)

type ::= condition?  simple_type

simple_type ::= type_app_id_or_tv | prod_or_power_type | func_type

prod_or_power_type ::= prod_type | power_type

type_id ::= upper letter*

param_t_var ::= 'T' digit

ad_hoc_t_var ::= '@' upper

type_app_id_or_tv ::=
types_in_paren? taioa_middle types_in_paren? | param_t_var

taioa_middle ::=
type_id ( types_in_paren letter+ )* | ad_hoc_t_var

types_in_paren ::= paren_start simple_type ( comma simple_type )* paren_end

prod_type ::= field_type ( ' x ' field_type )+

field_type ::= power_base_type | power_type

power_base_type ::=
type_app_id_or_tv | paren_start ( prod_type | func_type ) paren_end

power_type ::= power_base_type '^' int_greater_than_one

func_type ::= in_or_out_type ' => ' in_or_out_type

in_or_out_type ::=
type_app_id_or_tv | prod_or_power_type | paren_start func_type paren_end

condition ::= prop_name ' --> '

type_def ::= tuple_type_def | or_type_def

nl_double_space ::= nl '  '

space_or_nl_double_space ::= ' ' | nl_double_space

tuple_type_def ::=
'tuple type:' opt_space type_name equals prod_or_power_type nl
'field names:' space_or_nl_double_space field_names

type_name ::=
param_vars_in_paren? type_id ( param_vars_in_paren letter+ )*
param_vars_in_paren?

param_vars_in_paren ::=
paren_start param_t_var ( comma param_t_var )* paren_end

field_names ::= paren_start simple_ids paren_end

simple_ids ::= simple_id ( comma simple_id )+

or_type_def ::=
'or type:' opt_space type_name nl
'values:' or_type_values

or_type_values ::= opt_space or_type_values_line | or_type_values_lines

or_type_values_line ::= or_type_value (opt_space '|' opt_space or_type_value)*

or_type_values_lines ::=
nl_double_space or_type_values_line
(opt_space '|' nl_double_space or_type_values_line)*

or_type_value ::= simple_id internal_value?

internal_value ::=
'--<' opt_space identifier opt_space_colon simple_type opt_space '>'

opt_space_colon ::= opt_space ':' opt_space

t_nickname ::= 'type_nickname ' type_name equals simple_type

type_prop_def ::= atom_prop_def | renaming_prop_def

atom_prop_def ::=
prop_name_line nl 'needed' space_or_nl_double_space
identifier opt_space_colon simple_type

renaming_prop_def ::=
prop_name_line nl
'equivalent' space_or_nl_double_space prop_name ( comma prop_name )*

prop_name_line ::= 'type_proposition ' prop_name

prop_name ::=
upper ( name_part types_in_paren )+ name_part?
| " "( types_in_paren name_part )+ types_in_paren?

name_part ::= ( letter | '_'upper )+

type_theo ::=
'type_theorem ' prop_name_with_subs (' --> ' prop_name_with_subs)? nl
'proof' proof

prop_name_with_subs ::=
upper ( name_part subs_in_paren )+ name_part?
| " "( subs_in_paren name_part )+ subs_in_paren?

subs_in_paren ::=
paren_start t_var_sub ( comma t_var_sub )* paren_end

t_var_sub ::=
type_app_id_or_tv_sub | prod_or_power_type_sub | func_type_sub

prod_or_power_type_sub ::= prod_type_sub | power_type_sub

type_app_id_or_tv_sub ::=
subs_or_unders_in_paren? taioas_middle subs_or_unders_in_paren? | param_t_var

taioas_middle ::=
type_id ( subs_or_unders_in_paren letter+ )* | ad_hoc_t_var

subs_or_unders_in_paren ::=
paren_start sub_or_under ( comma sub_or_under )* paren_end

sub_or_under ::= t_var_sub | '_'

power_type_sub ::= power_base_type_sub '^' int_greater_than_one

power_base_type_sub ::=
'_' | type_app_id_or_tv_sub |
paren_start ( prod_type_sub | func_type_sub ) paren_end

prod_type_sub ::= field_type_sub ( ' x ' field_type_sub )+

field_type_sub ::= power_base_type_sub | power_type_sub

func_type_sub ::= in_or_out_type_sub ' => ' in_or_out_type_sub

in_or_out_type_sub ::=
'_' | type_app_id_or_tv_sub | prod_or_power_type_sub |
paren_start func_type_sub paren_end

proof ::= ' ' id_or_op_eq ' ' line_expr | nl '  ' id_or_op_eq  tt_value_expr

id_or_op_eq ::= identifier (op identifier)? ' ='

tt_value_expr ::= ' ' line_expr | nl_indent value_expr where_expr?

program ::= nl* program_part ( nl nl program_part )* nl*

program_part ::=
value_def_or_defs | type_def | t_nickname | type_prop_def | type_theo

nl ::= ( ' ' | 't' )* '\n'
